; Snake Game em Assembly 8086
; INI 51 - Professor Sergio Luiz Moral Marques
;
; Made  by
;
; Gustavo Mendes Oliveira             - RA: 20136
; Luiz Henrique Parolim Domingues     - RA: 21248
; Matheus Henrique de Oliveira Freire - RA: 21251

.MODEL SMALL
.STACK 100h
.DATA

.CODE
START:

    MOV SI, 1080
    
    CALL INIT_SCREEN


    ; INICIALIZAR O REGISTRADOR ES COM O ENDERECO DO VIDEO B800h
    MOV AX, 0B800h ; -> endereco de memoria de video
    MOV ES, AX

    XOR DI, DI ; -> ZERAMOS O PONTEIRO DAS 
               ;    POSICOES DA MEMORIA DE VIDEO

    ; LEMBRANDO NA MEMORIA DE VIDEO
    ; AH -> ATRIBUTO DO CARACTER
    ; AL -> CARACTER.

    MOV AX, 07DBh ; -> COR E CARACTER QUE FARAO A COBRA
    INT 10h

GAME_LOOP:

    CALL DELAY

    ; SE UMA LINHA TEM 80 CARACTERES POR EXEMPLO PARA A LINHA 1
    ; DEVEMOS COLOCAR DI EM QUE VALOR?
    ; DI = DI + 80 * 2
    MOV DI, SI
    MOV AX, 05DBh ; ATRIBUIMOS EM AX O CARACTER E SUA COR 
    MOV [ES]:DI, AX

    ; SE ZF SET NENHUM CARACTER FOI DIGITADO
    ; SE ZF CLEAR (0) CARACTER DIGITADO E VALOR EM AL
    ;JZ  INICIO_1

    CALL DELAY
    CALL DELAY
    CALL DELAY

    CALL READ_BUFFER ; SEMPRE CHAMAREMOS O PROCEDIMENTO PARA LER DO TECLADO
    JMP CHECK_PRESSED_KEYS ; IREMOS DIRETAMENTE PARA A VERIFICACAO DE TECLAS CASO O USUARIO NAO TENHA APERTADO NADA
    


CHECK_PRESSED_KEYS:
    CMP DL, 'w'
        JE UP
    CMP DL, 'a'
        JE LEFT
    CMP DL, 's'
        JE DOWN
    CMP DL, 'd'
        JE RIGHT        



    
    CMP DL, 01BH  ; COMPARA SE DIGITOU ESC PARA SAIR
        JE  FIM   ; SE DIGITOU ESC SAI DO JOGO

    JMP GAME_LOOP ; REPETE O JOGO

UP:
    SUB SI, 80
    JMP GAME_LOOP

DOWN:
    ADD SI, 80
    JMP GAME_LOOP

RIGHT:
    INC SI
    JMP GAME_LOOP

LEFT:
    DEC SI
    JMP GAME_LOOP



INICIO_1:
    ;MOV AL, 0DBh
    MOV AX, 07DBh
    JMP GAME_LOOP






FIM: ; fim do programa
    MOV AX, 4C00h
    INT 21h


;============================ PROCEDIMENTOS =======================================================




DELAY PROC ; PROCEDIMENTO DE DELAY PARA O JOGO
    XOR AX, AX
    MOV CX, 65535

    DELAYLOOP:

        CMP AX, CX
            LOOP DELAYLOOP
        
        RET
	
ENDP

INIT_SCREEN PROC

    MOV CX, 0000
    MOV DX, 184Fh
    INT 10h

    MOV AH, 02
    MOV BH, 00
    INT 10h
    
    RET

ENDP

READ_BUFFER PROC
    XOR AX, AX

    ; LER DADOS DO TECLADO SEM SER AUTO BLOCANTE.
    MOV AH, 1      ; DEFINIR FUNÇÃO 1H DA INTERRUPÇÃO 16H (VERIFICAÇÃO DE TECLADO)
    INT 16H        ; CHAMAR A INTERRUPÇÃO 16H

    JZ NO_KEY_PRESS ; VERIFICAR SE NENHUMA TECLA FOI PRESSIONADA

    MOV AH, 0      ; DEFINIR FUNÇÃO 0H DA INTERRUPÇÃO 16H (LEITURA DO TECLADO)
    INT 16H        ; CHAMAR A INTERRUPÇÃO 16H

    ; O CARACTERE ASCII DA TECLA PRESSIONADA ESTARA EM AL

    
    NO_KEY_PRESS:
        MOV DL, AL ; MOVEMOS AL PARA DL PARA MAIOR SEGURANCA EM SALVAR A ULTIMA TECLA SALVA
        XOR AH, AH

    RET
ENDP


END START