; Snake Game em Assembly 8086
; INI 51 - Professor Sergio Luiz Moral Marques
;
; Made  by
;
; Gustavo Mendes Oliveira             - RA: 20136
; Luiz Henrique Parolim Domingues     - RA: 21248
; Matheus Henrique de Oliveira Freire - RA: 21251

.MODEL SMALL
.STACK 100h
.DATA

.CODE
START:

    MOV SI, 1080
    
    CALL INIT_SCREEN


    ; INICIALIZAR O REGISTRADOR ES COM O ENDERECO DO VIDEO B800h
    MOV AX, 0B800h ; -> endereco de memoria de video
    MOV ES, AX

    XOR DI, DI ; -> ZERAMOS O PONTEIRO DAS 
               ;    POSICOES DA MEMORIA DE VIDEO

    ; LEMBRANDO NA MEMORIA DE VIDEO
    ; AH -> ATRIBUTO DO CARACTER
    ; AL -> CARACTER.

    MOV AX, 07DBh ; -> COR E CARACTER QUE FARAO A COBRA
    INT 10h

GAME_LOOP:

    CALL DELAY

    ; SE UMA LINHA TEM 80 CARACTERES POR EXEMPLO PARA A LINHA 1
    ; DEVEMOS COLOCAR DI EM QUE VALOR?
    ; DI = DI + 80 * 2
    MOV DI, SI
    MOV AX, 07DBh ; ATRIBUIMOS EM AX O CARACTER E SUA COR 
    MOV [ES]:DI, AX

    ; SE ZF SET NENHUM CARACTER FOI DIGITADO
    ; SE ZF CLEAR (0) CARACTER DIGITADO E VALOR EM AL
    ;JZ  INICIO_1

    XOR AX, AX      ; ZERAMOS O REGISTRADOR AX PARA NAO TERMOS PROBLEMAS NA VERIFICAO CASO NENHUMA TECLA SEJA APERTADA
    CALL READ_BUFFER ; SEMPRE CHAMAREMOS O PROCEDIMENTO PARA LER DO TECLADO

    CMP AL, 00h ; COMPARAMOS SE A PARTE BAIXA DE AX ESTA ZERADA, OU SEJA, O USUARIO NAO DIGITOU NADA
        JNE MOV_ALtoDL ; SE TIVER SIDO DIGITADO VAMOS PARA ONDE MOVEMOS O VALOR DE AL PARA DL

    JMP CHECK_PRESSED_KEYS ; IREMOS DIRETAMENTE PARA A VERIFICACAO DE TECLAS CASO O USUARIO NAO TENHA APERTADO NADA
    
MOV_ALtoDL:
    MOV DL, AL
    XOR AH, AH

CHECK_PRESSED_KEYS:
    CMP DL, 'w'
        JE UP
    CMP DL, 'a'
        JE LEFT
    CMP DL, 's'
        JE DOWN
    CMP DL, 'd'
        JE RIGHT        



    
    CMP DL, 01BH  ; COMPARA SE DIGITOU ESC PARA SAIR
        JE  FIM   ; SE DIGITOU ESC SAI DO JOGO

    JMP GAME_LOOP ; REPETE O JOGO

UP:
    SUB SI, 80
    JMP GAME_LOOP

DOWN:
    ADD SI, 80
    JMP GAME_LOOP

RIGHT:
    INC SI
    JMP GAME_LOOP

LEFT:
    DEC SI
    JMP GAME_LOOP



INICIO_1:
    ;MOV AL, 0DBh
    MOV AX, 07DBh
    JMP GAME_LOOP






FIM: ; fim do programa
    MOV AX, 4C00h
    INT 21h


;============================ PROCEDIMENTOS =======================================================




DELAY PROC ; PROCEDIMENTO DE DELAY PARA O JOGO
    XOR AX, AX
    MOV CX, 65535

    DELAYLOOP:

        CMP AX, CX
            LOOP DELAYLOOP
        
        RET
	
ENDP

INIT_SCREEN PROC

    MOV CX, 0000
    MOV DX, 184Fh
    INT 10h

    MOV AH, 02
    MOV BH, 00
    INT 10h
    
    RET

ENDP

READ_BUFFER PROC
    ; LER DADOS DO TECLADO SEM SER AUTO BLOCANTE.
    ;MOV AH, 06h ; Função 00h da interrupção 16h lê um caractere
    ;INT 21h     ; Interrupção 16h para ler o caractere digitado

    MOV AH, 0h
    INT 16h

    RET
ENDP


END START